### ISSUE TITLE
Amazon AWS download files path has changed, needs update

### ISSUE THREAD

**Issue by j0nnii** [signalkuppe/grunt-gathercontent#4]
Hi,

This tool is still working and I'm happy to use it. Thanks for that! However, one thing I've noticed is that "gathercontent-downloadfiles" task needs to be updated.

Change
https://gathercontent.s3.amazonaws.com/
to
https://gathercontent-production-uploads.s3.amazonaws.com/

**Comment by signalkuppe** [comment]
Hi @j0nnii thanks for the feedback, I'll check it as soon as possible.

**Comment by signalkuppe** [comment]
Fixed resources url and updated packages
